"""Shared authentication lifecycle constants.

Centralizing these values prevents the refresh-token contract from drifting
between routes, JWT helpers, cache helpers, tests, and documentation.
"""

from __future__ import annotations

import os


# Token/cookie names ----------------------------------------------------------
ACCESS_TOKEN_TYPE = "access_token"
REFRESH_TOKEN_TYPE = "refresh_token"
TOKEN_TYPE_BEARER = "Bearer"

ACCESS_COOKIE_NAME = "session_token"
REFRESH_COOKIE_NAME = "refresh_token"

ACCESS_COOKIE_PATH = "/"
REFRESH_COOKIE_PATH = "/auth"
COOKIE_HTTPONLY = True
COOKIE_SECURE = True
COOKIE_SAMESITE = "strict"


# Scope markers ---------------------------------------------------------------
AUTH_SCOPE_PROJECT = "project"
AUTH_SCOPE_PLATFORM = "platform"
PLATFORM_COLLECTION_SENTINEL = "__platform__"


# Redis key prefixes ----------------------------------------------------------
SESSION_PREFIX = "session:"
SESSION_FULL_PREFIX = "session_full:"
REFRESH_FAMILY_PREFIX = "refresh_family:"
REFRESH_TOKEN_PREFIX = "refresh_token:"
REFRESH_ANCHOR_PREFIX = "refresh_anchor:"
REFRESH_USED_PREFIX = "refresh_used:"
REVOKED_FAMILY_PREFIX = "revoked_family:"
USER_SESSIONS_PREFIX = "user_sessions:"
USER_REFRESH_FAMILIES_PREFIX = "user_refresh_families:"
EMAIL_RATE_PREFIX = "email_rate:"
EMAIL_COOLDOWN_PREFIX = "email_cooldown:"
EMAIL_IDEMPOTENCY_CACHE_PREFIX = "email_idem:"
EMAIL_WEBHOOK_EVENT_PREFIX = "email_webhook_event:"
EMAIL_WORKER_WAKE_PREFIX = "email_worker_wake:"
AUTH_CHANGE_PASSWORD_RATE_PREFIX = "auth_change_password_rate:"

# Google OAuth/provider-init Redis key prefixes -------------------------------
GOOGLE_OAUTH_STATE_PREFIX = "google_oauth_state:"
GOOGLE_OAUTH_STATE_CONSUMED_PREFIX = "google_oauth_state_consumed:"
GOOGLE_OAUTH_LINK_TOKEN_PREFIX = "google_oauth_link:"
GOOGLE_OAUTH_RECENT_REAUTH_PREFIX = "google_oauth_reauth:"
GOOGLE_OAUTH_JWKS_CACHE_PREFIX = "google_oauth_jwks:"
GOOGLE_OAUTH_RATE_PREFIX = "google_oauth_rate:"
GOOGLE_OAUTH_START_RATE_PREFIX = "google_oauth_rate:start:"
GOOGLE_OAUTH_CALLBACK_RATE_PREFIX = "google_oauth_rate:callback:"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_PREFIX = "google_oauth_rate:provider_init:"
GOOGLE_OAUTH_STATE_CONSUME_RATE_PREFIX = "google_oauth_rate:state_consume:"
GOOGLE_OAUTH_SUB_COLLISION_RATE_PREFIX = "google_oauth_rate:sub_collision:"
GOOGLE_OAUTH_LINK_TOKEN_RATE_PREFIX = "google_oauth_rate:link_token:"
GOOGLE_OAUTH_JWKS_FETCH_RATE_PREFIX = "google_oauth_rate:jwks_fetch:"
GOOGLE_OAUTH_UNLINK_RATE_PREFIX = "google_oauth_rate:unlink:"
PROVIDER_INIT_REDEEM_CACHE_PREFIX = "provider_init_redeem:"

# Patreon account-link Redis key prefixes -------------------------------------
# All Patreon rate-limit/storage helpers MUST append only pre-hashed bucket
# material to these prefixes. Raw provider IDs, emails, IPs, tokens, campaign
# IDs, tier IDs, or fingerprints do not belong in Redis keys.
PATREON_LINK_REQUEST_PREFIX = "patreon_link_request:"
PATREON_PROOF_REQUEST_PREFIX = "patreon_proof_request:"
PATREON_PROOF_TOKEN_PREFIX = "patreon_proof_token:"
PATREON_PROOF_CONSUME_PREFIX = "patreon_proof_consume:"
PATREON_UNLINK_PREFIX = "patreon_unlink:"
PATREON_LINK_STATUS_PREFIX = "patreon_link_status:"
PATREON_S2S_ENTITLEMENT_PREFIX = "patreon_s2s_entitlement:"
PATREON_WEBHOOK_DELIVERY_PREFIX = "patreon_webhook_delivery:"
PATREON_WEBHOOK_SIGNATURE_FAILURE_PREFIX = "patreon_webhook_signature_failure:"
PATREON_SYNC_ENQUEUE_PREFIX = "patreon_sync_enqueue:"
PATREON_SYNC_JOB_PREFIX = "patreon_sync_job:"
PATREON_SYNC_LOCK_PREFIX = "patreon_sync_lock:"
PATREON_CREATOR_TOKEN_REFRESH_PREFIX = "patreon_creator_token_refresh:"

PATREON_LINK_REQUEST_RATE_PREFIX = "patreon_rate:link_request:"
PATREON_PROOF_REQUEST_RATE_PREFIX = "patreon_rate:proof_request:"
PATREON_PROOF_CONSUME_RATE_PREFIX = "patreon_rate:proof_consume:"
PATREON_UNLINK_RATE_PREFIX = "patreon_rate:unlink:"
PATREON_STATUS_RATE_PREFIX = "patreon_rate:status:"
PATREON_S2S_RATE_PREFIX = "patreon_rate:s2s:"
PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_PREFIX = "patreon_rate:webhook_signature_failure:"
PATREON_SYNC_ENQUEUE_RATE_PREFIX = "patreon_rate:sync_enqueue:"
PATREON_API_CLIENT_RATE_PREFIX = "patreon_rate:api_client:"
PATREON_API_ACCESS_TOKEN_RATE_PREFIX = "patreon_rate:api_access_token:"
PATREON_API_EDGE_4XX_RATE_PREFIX = "patreon_rate:api_edge_4xx:"


# TTL/config names ------------------------------------------------------------
REFRESH_FAMILY_TTL_SECONDS = 72 * 60 * 60
REMEMBER_ME_REFRESH_TTL_SECONDS = 30 * 24 * 60 * 60
JWT_ACCESS_TOKEN_EXPIRE_MINUTES_ENV = "JWT_ACCESS_TOKEN_EXPIRE_MINUTES"
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = int(
    os.environ.get(JWT_ACCESS_TOKEN_EXPIRE_MINUTES_ENV, "15")
)


# Transactional auth email config names ---------------------------------------
EMAIL_DELIVERY_ENABLED_ENV = "EMAIL_DELIVERY_ENABLED"
EMAIL_PROVIDER_ENV = "EMAIL_PROVIDER"
EMAIL_ALLOW_REAL_SEND_IN_TESTS_ENV = "EMAIL_ALLOW_REAL_SEND_IN_TESTS"
EMAIL_FROM_ADDRESS_ENV = "EMAIL_FROM_ADDRESS"
EMAIL_REPLY_TO_ADDRESS_ENV = "EMAIL_REPLY_TO_ADDRESS"
EMAIL_SENDER_DOMAIN_VERIFIED_ENV = "EMAIL_SENDER_DOMAIN_VERIFIED"

RESEND_API_KEY_ENV = "RESEND_API_KEY"
RESEND_WEBHOOK_SECRET_ENV = "RESEND_WEBHOOK_SECRET"
RESEND_WEBHOOK_TOLERANCE_SECONDS_ENV = "RESEND_WEBHOOK_TOLERANCE_SECONDS"

MAILPIT_SMTP_HOST_ENV = "MAILPIT_SMTP_HOST"
MAILPIT_SMTP_PORT_ENV = "MAILPIT_SMTP_PORT"
MAILPIT_API_BASE_URL_ENV = "MAILPIT_API_BASE_URL"

EMAIL_TOKEN_PEPPER_ENV = "EMAIL_TOKEN_PEPPER"
EMAIL_HASH_PEPPER_ENV = "EMAIL_HASH_PEPPER"
EMAIL_IDEMPOTENCY_PEPPER_ENV = "EMAIL_IDEMPOTENCY_PEPPER"
EMAIL_PAYLOAD_KEY_ENV = "EMAIL_PAYLOAD_KEY"

EMAIL_ACTIVATION_TOKEN_TTL_SECONDS_ENV = "EMAIL_ACTIVATION_TOKEN_TTL_SECONDS"
EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS_ENV = "EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS"
EMAIL_IDEMPOTENCY_TTL_SECONDS_ENV = "EMAIL_IDEMPOTENCY_TTL_SECONDS"
EMAIL_TERMINAL_RETENTION_DAYS_ENV = "EMAIL_TERMINAL_RETENTION_DAYS"
EMAIL_DELIVERY_ATTEMPT_RETENTION_DAYS_ENV = "EMAIL_DELIVERY_ATTEMPT_RETENTION_DAYS"

EMAIL_SEND_RECIPIENT_HOURLY_LIMIT_ENV = "EMAIL_SEND_RECIPIENT_HOURLY_LIMIT"
EMAIL_SEND_RECIPIENT_DAILY_LIMIT_ENV = "EMAIL_SEND_RECIPIENT_DAILY_LIMIT"
EMAIL_SEND_USER_HOURLY_LIMIT_ENV = "EMAIL_SEND_USER_HOURLY_LIMIT"
EMAIL_SEND_IP_HOURLY_LIMIT_ENV = "EMAIL_SEND_IP_HOURLY_LIMIT"
EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT_ENV = "EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT"
EMAIL_CONSUME_IP_HOURLY_LIMIT_ENV = "EMAIL_CONSUME_IP_HOURLY_LIMIT"
EMAIL_RESEND_COOLDOWN_SECONDS_ENV = "EMAIL_RESEND_COOLDOWN_SECONDS"
EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT_ENV = "EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT"
EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS_ENV = "EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS"

PASSWORD_POLICY_MIN_LENGTH_ENV = "PASSWORD_POLICY_MIN_LENGTH"
PASSWORD_POLICY_WEAK_DENYLIST_ENV = "PASSWORD_POLICY_WEAK_DENYLIST"

AUTH_CHANGE_PASSWORD_FAILURE_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_FAILURE_LIMIT"
AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS_ENV = "AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS"
AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT"
AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT"
AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT"

EMAIL_WORKER_POLL_SECONDS_ENV = "EMAIL_WORKER_POLL_SECONDS"
EMAIL_WORKER_BATCH_SIZE_ENV = "EMAIL_WORKER_BATCH_SIZE"
EMAIL_WORKER_LEASE_SECONDS_ENV = "EMAIL_WORKER_LEASE_SECONDS"
EMAIL_WORKER_MAX_ATTEMPTS_ENV = "EMAIL_WORKER_MAX_ATTEMPTS"
EMAIL_WORKER_BACKOFF_SECONDS_ENV = "EMAIL_WORKER_BACKOFF_SECONDS"
EMAIL_RETENTION_PURGE_INTERVAL_SECONDS_ENV = "EMAIL_RETENTION_PURGE_INTERVAL_SECONDS"


# Google OAuth/provider-init config names -------------------------------------
GOOGLE_OAUTH_ENABLED_ENV = "GOOGLE_OAUTH_ENABLED"
GOOGLE_OAUTH_CLIENT_ID_ENV = "GOOGLE_OAUTH_CLIENT_ID"
GOOGLE_OAUTH_CLIENT_SECRET_ENV = "GOOGLE_OAUTH_CLIENT_SECRET"
GOOGLE_OAUTH_DISCOVERY_URL_ENV = "GOOGLE_OAUTH_DISCOVERY_URL"
GOOGLE_OAUTH_AUTHORIZE_ENDPOINT_ENV = "GOOGLE_OAUTH_AUTHORIZE_ENDPOINT"
GOOGLE_OAUTH_TOKEN_ENDPOINT_ENV = "GOOGLE_OAUTH_TOKEN_ENDPOINT"
GOOGLE_OAUTH_JWKS_URI_ENV = "GOOGLE_OAUTH_JWKS_URI"
GOOGLE_OAUTH_ISSUERS_ENV = "GOOGLE_OAUTH_ISSUERS"
GOOGLE_OAUTH_SCOPES_ENV = "GOOGLE_OAUTH_SCOPES"
GOOGLE_OAUTH_REDIRECT_URIS_ENV = "GOOGLE_OAUTH_REDIRECT_URIS"
GOOGLE_OAUTH_RETURN_ORIGINS_ENV = "GOOGLE_OAUTH_RETURN_ORIGINS"
GOOGLE_OAUTH_ALLOWED_HOSTED_DOMAINS_ENV = "GOOGLE_OAUTH_ALLOWED_HOSTED_DOMAINS"
GOOGLE_OAUTH_PROVISIONING_MODE_ENV = "GOOGLE_OAUTH_PROVISIONING_MODE"
GOOGLE_OAUTH_DEFAULT_USER_GROUP_HASH_ENV = "GOOGLE_OAUTH_DEFAULT_USER_GROUP_HASH"
GOOGLE_OAUTH_STATE_TTL_SECONDS_ENV = "GOOGLE_OAUTH_STATE_TTL_SECONDS"
GOOGLE_OAUTH_LINK_TOKEN_TTL_SECONDS_ENV = "GOOGLE_OAUTH_LINK_TOKEN_TTL_SECONDS"
GOOGLE_OAUTH_RECENT_REAUTH_SECONDS_ENV = "GOOGLE_OAUTH_RECENT_REAUTH_SECONDS"
GOOGLE_OAUTH_JWKS_CACHE_TTL_SECONDS_ENV = "GOOGLE_OAUTH_JWKS_CACHE_TTL_SECONDS"
GOOGLE_OAUTH_LEEWAY_SECONDS_ENV = "GOOGLE_OAUTH_LEEWAY_SECONDS"
GOOGLE_OAUTH_STATE_PEPPER_ENV = "GOOGLE_OAUTH_STATE_PEPPER"
GOOGLE_OAUTH_PROVIDER_SUB_PEPPER_ENV = "GOOGLE_OAUTH_PROVIDER_SUB_PEPPER"
GOOGLE_OAUTH_EMAIL_HASH_PEPPER_ENV = "GOOGLE_OAUTH_EMAIL_HASH_PEPPER"
GOOGLE_OAUTH_PASSWORDLESS_HASH_SECRET_ENV = "GOOGLE_OAUTH_PASSWORDLESS_HASH_SECRET"
GOOGLE_OAUTH_FAIL_CLOSED_ON_REDIS_ERROR_ENV = "GOOGLE_OAUTH_FAIL_CLOSED_ON_REDIS_ERROR"
PROVIDER_INIT_REDEEM_URL_ENV = "PROVIDER_INIT_REDEEM_URL"
PROVIDER_INIT_REDEEM_TOKEN_ENV = "PROVIDER_INIT_REDEEM_TOKEN"
PROVIDER_INIT_RETURN_ORIGINS_ENV = "PROVIDER_INIT_RETURN_ORIGINS"

GOOGLE_OAUTH_START_RATE_LIMIT_ENV = "GOOGLE_OAUTH_START_RATE_LIMIT"
GOOGLE_OAUTH_START_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_START_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_CALLBACK_RATE_LIMIT_ENV = "GOOGLE_OAUTH_CALLBACK_RATE_LIMIT"
GOOGLE_OAUTH_CALLBACK_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_CALLBACK_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_LIMIT_ENV = "GOOGLE_OAUTH_PROVIDER_INIT_RATE_LIMIT"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_PROVIDER_INIT_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_STATE_CONSUME_RATE_LIMIT_ENV = "GOOGLE_OAUTH_STATE_CONSUME_RATE_LIMIT"
GOOGLE_OAUTH_STATE_CONSUME_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_STATE_CONSUME_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_SUB_COLLISION_RATE_LIMIT_ENV = "GOOGLE_OAUTH_SUB_COLLISION_RATE_LIMIT"
GOOGLE_OAUTH_SUB_COLLISION_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_SUB_COLLISION_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_LINK_TOKEN_RATE_LIMIT_ENV = "GOOGLE_OAUTH_LINK_TOKEN_RATE_LIMIT"
GOOGLE_OAUTH_LINK_TOKEN_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_LINK_TOKEN_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_JWKS_FETCH_RATE_LIMIT_ENV = "GOOGLE_OAUTH_JWKS_FETCH_RATE_LIMIT"
GOOGLE_OAUTH_JWKS_FETCH_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_JWKS_FETCH_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_UNLINK_RATE_LIMIT_ENV = "GOOGLE_OAUTH_UNLINK_RATE_LIMIT"
GOOGLE_OAUTH_UNLINK_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_UNLINK_RATE_WINDOW_SECONDS"


# Patreon account-link config names -------------------------------------------
PATREON_PROVIDER_NAME = "patreon"

# Disabled-by-default kill switches. Missing/false means no new Patreon behavior
# is allowed; existing local auth, Google OAuth, sessions, and /auth/validate are
# deliberately unaffected.
PATREON_LINKING_ENABLED_ENV = "PATREON_LINKING_ENABLED"
PATREON_WEBHOOKS_ENABLED_ENV = "PATREON_WEBHOOKS_ENABLED"
PATREON_SYNC_ENABLED_ENV = "PATREON_SYNC_ENABLED"
PATREON_S2S_ENTITLEMENT_ENABLED_ENV = "PATREON_S2S_ENTITLEMENT_ENABLED"
PATREON_CREATOR_TOKEN_REFRESH_ENABLED_ENV = "PATREON_CREATOR_TOKEN_REFRESH_ENABLED"
PATREON_RAW_PAYLOAD_CAPTURE_ENABLED_ENV = "PATREON_RAW_PAYLOAD_CAPTURE_ENABLED"

PATREON_API_BASE_URL_ENV = "PATREON_API_BASE_URL"
PATREON_OAUTH_TOKEN_URL_ENV = "PATREON_OAUTH_TOKEN_URL"
PATREON_CREATOR_ACCESS_TOKEN_ENV = "PATREON_CREATOR_ACCESS_TOKEN"
PATREON_CREATOR_REFRESH_TOKEN_ENV = "PATREON_CREATOR_REFRESH_TOKEN"
PATREON_CLIENT_ID_ENV = "PATREON_CLIENT_ID"
PATREON_CLIENT_SECRET_ENV = "PATREON_CLIENT_SECRET"
PATREON_WEBHOOK_SECRET_ENV = "PATREON_WEBHOOK_SECRET"
PATREON_WEBHOOK_ID_ENV = "PATREON_WEBHOOK_ID"
PATREON_S2S_BEARER_TOKEN_ENV = "PATREON_S2S_BEARER_TOKEN"
PATREON_USER_AGENT_ENV = "PATREON_USER_AGENT"
PATREON_CAMPAIGN_IDS_ENV = "PATREON_CAMPAIGN_IDS"
PATREON_CAMPAIGN_TIER_MAP_ENV = "PATREON_CAMPAIGN_TIER_MAP"
PATREON_TIER_MAP_JSON_ENV = "PATREON_TIER_MAP_JSON"
PATREON_TIER_MAP_FILE_ENV = "PATREON_TIER_MAP_FILE"
PATREON_ALLOWED_WEBHOOK_EVENTS_ENV = "PATREON_ALLOWED_WEBHOOK_EVENTS"

PATREON_PROVIDER_SUB_PEPPER_ENV = "PATREON_PROVIDER_SUB_PEPPER"
PATREON_EMAIL_HASH_PEPPER_ENV = "PATREON_EMAIL_HASH_PEPPER"
PATREON_PROOF_TOKEN_PEPPER_ENV = "PATREON_PROOF_TOKEN_PEPPER"
PATREON_ID_HMAC_SECRET_ENV = "PATREON_ID_HMAC_SECRET"
PATREON_HMAC_SECRET_ENV = "PATREON_HMAC_SECRET"
PATREON_WEBHOOK_DELIVERY_HASH_PEPPER_ENV = "PATREON_WEBHOOK_DELIVERY_HASH_PEPPER"
PATREON_PROVIDER_TOKEN_ENCRYPTION_KEY_ENV = "PATREON_PROVIDER_TOKEN_ENCRYPTION_KEY"
PATREON_PROVIDER_TOKEN_ENCRYPTION_KEY_ID_ENV = "PATREON_PROVIDER_TOKEN_ENCRYPTION_KEY_ID"

PATREON_PROOF_TOKEN_TTL_SECONDS_ENV = "PATREON_PROOF_TOKEN_TTL_SECONDS"
PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS_ENV = "PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS"
PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS_ENV = "PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS"
PATREON_RAW_PAYLOAD_RETENTION_DAYS_ENV = "PATREON_RAW_PAYLOAD_RETENTION_DAYS"

PATREON_API_TIMEOUT_SECONDS_ENV = "PATREON_API_TIMEOUT_SECONDS"
PATREON_API_CONNECT_TIMEOUT_SECONDS_ENV = "PATREON_API_CONNECT_TIMEOUT_SECONDS"
PATREON_API_PAGE_SIZE_ENV = "PATREON_API_PAGE_SIZE"
PATREON_API_MAX_PAGES_PER_SYNC_ENV = "PATREON_API_MAX_PAGES_PER_SYNC"
PATREON_API_RETRY_MAX_ATTEMPTS_ENV = "PATREON_API_RETRY_MAX_ATTEMPTS"
PATREON_API_RETRY_BACKOFF_SECONDS_ENV = "PATREON_API_RETRY_BACKOFF_SECONDS"
PATREON_API_RETRY_JITTER_SECONDS_ENV = "PATREON_API_RETRY_JITTER_SECONDS"
PATREON_CREATOR_TOKEN_REFRESH_MARGIN_SECONDS_ENV = "PATREON_CREATOR_TOKEN_REFRESH_MARGIN_SECONDS"

PATREON_SYNC_INTERVAL_SECONDS_ENV = "PATREON_SYNC_INTERVAL_SECONDS"
PATREON_SYNC_JITTER_SECONDS_ENV = "PATREON_SYNC_JITTER_SECONDS"
PATREON_SYNC_STALE_AFTER_SECONDS_ENV = "PATREON_SYNC_STALE_AFTER_SECONDS"
PATREON_SYNC_WORKER_POLL_SECONDS_ENV = "PATREON_SYNC_WORKER_POLL_SECONDS"
PATREON_SYNC_WORKER_BATCH_SIZE_ENV = "PATREON_SYNC_WORKER_BATCH_SIZE"
PATREON_SYNC_JOB_LEASE_SECONDS_ENV = "PATREON_SYNC_JOB_LEASE_SECONDS"
PATREON_SYNC_MAX_ATTEMPTS_ENV = "PATREON_SYNC_MAX_ATTEMPTS"
PATREON_SYNC_BACKOFF_SECONDS_ENV = "PATREON_SYNC_BACKOFF_SECONDS"
PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_LIMIT_ENV = "PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_LIMIT"
PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_WINDOW_SECONDS_ENV = (
    "PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_WINDOW_SECONDS"
)

PATREON_LINK_REQUEST_RATE_LIMIT_ENV = "PATREON_LINK_REQUEST_RATE_LIMIT"
PATREON_LINK_REQUEST_RATE_WINDOW_SECONDS_ENV = "PATREON_LINK_REQUEST_RATE_WINDOW_SECONDS"
PATREON_PROOF_REQUEST_RATE_LIMIT_ENV = "PATREON_PROOF_REQUEST_RATE_LIMIT"
PATREON_PROOF_REQUEST_RATE_WINDOW_SECONDS_ENV = "PATREON_PROOF_REQUEST_RATE_WINDOW_SECONDS"
PATREON_PROOF_CONSUME_RATE_LIMIT_ENV = "PATREON_PROOF_CONSUME_RATE_LIMIT"
PATREON_PROOF_CONSUME_RATE_WINDOW_SECONDS_ENV = "PATREON_PROOF_CONSUME_RATE_WINDOW_SECONDS"
PATREON_UNLINK_RATE_LIMIT_ENV = "PATREON_UNLINK_RATE_LIMIT"
PATREON_UNLINK_RATE_WINDOW_SECONDS_ENV = "PATREON_UNLINK_RATE_WINDOW_SECONDS"
PATREON_STATUS_RATE_LIMIT_ENV = "PATREON_STATUS_RATE_LIMIT"
PATREON_STATUS_RATE_WINDOW_SECONDS_ENV = "PATREON_STATUS_RATE_WINDOW_SECONDS"
PATREON_S2S_RATE_LIMIT_ENV = "PATREON_S2S_RATE_LIMIT"
PATREON_S2S_RATE_WINDOW_SECONDS_ENV = "PATREON_S2S_RATE_WINDOW_SECONDS"
PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_LIMIT_ENV = "PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_LIMIT"
PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_WINDOW_SECONDS_ENV = (
    "PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_WINDOW_SECONDS"
)
PATREON_SYNC_ENQUEUE_RATE_LIMIT_ENV = "PATREON_SYNC_ENQUEUE_RATE_LIMIT"
PATREON_SYNC_ENQUEUE_RATE_WINDOW_SECONDS_ENV = "PATREON_SYNC_ENQUEUE_RATE_WINDOW_SECONDS"
PATREON_API_CLIENT_RATE_LIMIT_ENV = "PATREON_API_CLIENT_RATE_LIMIT"
PATREON_API_CLIENT_RATE_WINDOW_SECONDS_ENV = "PATREON_API_CLIENT_RATE_WINDOW_SECONDS"
PATREON_API_ACCESS_TOKEN_RATE_LIMIT_ENV = "PATREON_API_ACCESS_TOKEN_RATE_LIMIT"
PATREON_API_ACCESS_TOKEN_RATE_WINDOW_SECONDS_ENV = "PATREON_API_ACCESS_TOKEN_RATE_WINDOW_SECONDS"
PATREON_API_EDGE_4XX_RATE_LIMIT_ENV = "PATREON_API_EDGE_4XX_RATE_LIMIT"
PATREON_API_EDGE_4XX_RATE_WINDOW_SECONDS_ENV = "PATREON_API_EDGE_4XX_RATE_WINDOW_SECONDS"

RUN_PATREON_LOCAL_E2E_ENV = "RUN_PATREON_LOCAL_E2E"
RUN_PATREON_E2E_ENV = "RUN_PATREON_E2E"
PATREON_LIVE_TEST_USER_HASH_ENV = "PATREON_LIVE_TEST_USER_HASH"
PATREON_TEST_CAMPAIGN_ID_ENV = "PATREON_TEST_CAMPAIGN_ID"
PATREON_TEST_MEMBER_EMAIL_ENV = "PATREON_TEST_MEMBER_EMAIL"
PATREON_E2E_CREATOR_TOKEN_ENV = "PATREON_E2E_CREATOR_TOKEN"

GOOGLE_OAUTH_PROVISIONING_DISABLED = "disabled"
GOOGLE_OAUTH_PROVISIONING_LINK_ONLY = "link_only"
GOOGLE_OAUTH_PROVISIONING_AUTO_CREATE = "auto_create"
GOOGLE_OAUTH_PROVISIONING_BOTH = "both"
GOOGLE_OAUTH_ALLOWED_PROVISIONING_MODES = {
    GOOGLE_OAUTH_PROVISIONING_DISABLED,
    GOOGLE_OAUTH_PROVISIONING_LINK_ONLY,
    GOOGLE_OAUTH_PROVISIONING_AUTO_CREATE,
    GOOGLE_OAUTH_PROVISIONING_BOTH,
}
GOOGLE_OAUTH_DEFAULT_SCOPES = "openid email"


# Patreon account-link defaults ------------------------------------------------
DEFAULT_PATREON_LINKING_ENABLED = False
DEFAULT_PATREON_WEBHOOKS_ENABLED = False
DEFAULT_PATREON_SYNC_ENABLED = False
DEFAULT_PATREON_S2S_ENTITLEMENT_ENABLED = False
DEFAULT_PATREON_CREATOR_TOKEN_REFRESH_ENABLED = False
DEFAULT_PATREON_RAW_PAYLOAD_CAPTURE_ENABLED = False

PATREON_FEATURE_FLAG_ENV_NAMES = (
    PATREON_LINKING_ENABLED_ENV,
    PATREON_WEBHOOKS_ENABLED_ENV,
    PATREON_SYNC_ENABLED_ENV,
    PATREON_S2S_ENTITLEMENT_ENABLED_ENV,
    PATREON_CREATOR_TOKEN_REFRESH_ENABLED_ENV,
    PATREON_RAW_PAYLOAD_CAPTURE_ENABLED_ENV,
)
PATREON_KILL_SWITCH_ENV_NAMES = PATREON_FEATURE_FLAG_ENV_NAMES
PATREON_FEATURE_FLAG_DEFAULTS = {
    PATREON_LINKING_ENABLED_ENV: DEFAULT_PATREON_LINKING_ENABLED,
    PATREON_WEBHOOKS_ENABLED_ENV: DEFAULT_PATREON_WEBHOOKS_ENABLED,
    PATREON_SYNC_ENABLED_ENV: DEFAULT_PATREON_SYNC_ENABLED,
    PATREON_S2S_ENTITLEMENT_ENABLED_ENV: DEFAULT_PATREON_S2S_ENTITLEMENT_ENABLED,
    PATREON_CREATOR_TOKEN_REFRESH_ENABLED_ENV: DEFAULT_PATREON_CREATOR_TOKEN_REFRESH_ENABLED,
    PATREON_RAW_PAYLOAD_CAPTURE_ENABLED_ENV: DEFAULT_PATREON_RAW_PAYLOAD_CAPTURE_ENABLED,
}

DEFAULT_PATREON_API_BASE_URL = "https://www.patreon.com/api/oauth2/v2"
DEFAULT_PATREON_OAUTH_TOKEN_URL = "https://www.patreon.com/api/oauth2/token"
DEFAULT_PATREON_USER_AGENT = "api.auth-patreon-sync/1.0"
DEFAULT_PATREON_API_TIMEOUT_SECONDS = 15
DEFAULT_PATREON_API_CONNECT_TIMEOUT_SECONDS = 5
DEFAULT_PATREON_API_PAGE_SIZE = 1000
MAX_PATREON_API_PAGE_SIZE = 1000
PATREON_PLEDGE_HISTORY_PAGE_SIZE = 500
DEFAULT_PATREON_API_MAX_PAGES_PER_SYNC = 0  # 0 = no local page cap; provider rate limits still apply.
DEFAULT_PATREON_API_RETRY_MAX_ATTEMPTS = 3
DEFAULT_PATREON_API_RETRY_BACKOFF_SECONDS = (1, 5, 15)
DEFAULT_PATREON_API_RETRY_JITTER_SECONDS = 5
DEFAULT_PATREON_CREATOR_TOKEN_REFRESH_MARGIN_SECONDS = 7 * 24 * 60 * 60

DEFAULT_PATREON_PROOF_TOKEN_TTL_SECONDS = 15 * 60
DEFAULT_PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS = 24
MAX_PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS = 24
DEFAULT_PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS = 90
MAX_PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS = 90
DEFAULT_PATREON_RAW_PAYLOAD_RETENTION_DAYS = 30
MAX_PATREON_RAW_PAYLOAD_RETENTION_DAYS = 30
PATREON_LINK_HISTORY_RETENTION = "indefinite"
PATREON_SNAPSHOT_HISTORY_RETENTION = "indefinite"
PATREON_UNLINK_HISTORY_RETENTION = "indefinite"

PATREON_RETENTION_DEFAULTS = {
    PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS_ENV: DEFAULT_PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS,
    PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS_ENV: DEFAULT_PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS,
    PATREON_RAW_PAYLOAD_RETENTION_DAYS_ENV: DEFAULT_PATREON_RAW_PAYLOAD_RETENTION_DAYS,
}
PATREON_RETENTION_CAPS = {
    PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS_ENV: MAX_PATREON_PROOF_RETENTION_AFTER_EXPIRY_HOURS,
    PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS_ENV: MAX_PATREON_WEBHOOK_DELIVERY_RETENTION_DAYS,
    PATREON_RAW_PAYLOAD_RETENTION_DAYS_ENV: MAX_PATREON_RAW_PAYLOAD_RETENTION_DAYS,
}
PATREON_INDEFINITE_RETENTION_BUCKETS = (
    "patreon_link_history",
    "patreon_member_snapshots",
    "patreon_entitlement_history",
    "patreon_unlink_history",
)

DEFAULT_PATREON_LINK_REQUEST_RATE_LIMIT = 5
DEFAULT_PATREON_LINK_REQUEST_RATE_WINDOW_SECONDS = 60 * 60
DEFAULT_PATREON_PROOF_REQUEST_RATE_LIMIT = 3
DEFAULT_PATREON_PROOF_REQUEST_RATE_WINDOW_SECONDS = 60 * 60
DEFAULT_PATREON_PROOF_CONSUME_RATE_LIMIT = 5
DEFAULT_PATREON_PROOF_CONSUME_RATE_WINDOW_SECONDS = 15 * 60
DEFAULT_PATREON_UNLINK_RATE_LIMIT = 5
DEFAULT_PATREON_UNLINK_RATE_WINDOW_SECONDS = 5 * 60
DEFAULT_PATREON_STATUS_RATE_LIMIT = 60
DEFAULT_PATREON_STATUS_RATE_WINDOW_SECONDS = 60
DEFAULT_PATREON_S2S_RATE_LIMIT = 120
DEFAULT_PATREON_S2S_RATE_WINDOW_SECONDS = 60
DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_LIMIT = 30
DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_WINDOW_SECONDS = 60
DEFAULT_PATREON_SYNC_ENQUEUE_RATE_LIMIT = 30
DEFAULT_PATREON_SYNC_ENQUEUE_RATE_WINDOW_SECONDS = 5 * 60
DEFAULT_PATREON_API_CLIENT_RATE_LIMIT = 100
DEFAULT_PATREON_API_CLIENT_RATE_WINDOW_SECONDS = 2
DEFAULT_PATREON_API_ACCESS_TOKEN_RATE_LIMIT = 100
DEFAULT_PATREON_API_ACCESS_TOKEN_RATE_WINDOW_SECONDS = 60
DEFAULT_PATREON_API_EDGE_4XX_RATE_LIMIT = 2000
DEFAULT_PATREON_API_EDGE_4XX_RATE_WINDOW_SECONDS = 10 * 60

PATREON_RATE_LIMIT_ENV_NAMES = {
    "link_request": (
        PATREON_LINK_REQUEST_RATE_LIMIT_ENV,
        PATREON_LINK_REQUEST_RATE_WINDOW_SECONDS_ENV,
    ),
    "proof_request": (
        PATREON_PROOF_REQUEST_RATE_LIMIT_ENV,
        PATREON_PROOF_REQUEST_RATE_WINDOW_SECONDS_ENV,
    ),
    "proof_consume": (
        PATREON_PROOF_CONSUME_RATE_LIMIT_ENV,
        PATREON_PROOF_CONSUME_RATE_WINDOW_SECONDS_ENV,
    ),
    "unlink": (PATREON_UNLINK_RATE_LIMIT_ENV, PATREON_UNLINK_RATE_WINDOW_SECONDS_ENV),
    "status": (PATREON_STATUS_RATE_LIMIT_ENV, PATREON_STATUS_RATE_WINDOW_SECONDS_ENV),
    "s2s": (PATREON_S2S_RATE_LIMIT_ENV, PATREON_S2S_RATE_WINDOW_SECONDS_ENV),
    "webhook_signature_failure": (
        PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_LIMIT_ENV,
        PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_WINDOW_SECONDS_ENV,
    ),
    "sync_enqueue": (
        PATREON_SYNC_ENQUEUE_RATE_LIMIT_ENV,
        PATREON_SYNC_ENQUEUE_RATE_WINDOW_SECONDS_ENV,
    ),
    "api_client": (
        PATREON_API_CLIENT_RATE_LIMIT_ENV,
        PATREON_API_CLIENT_RATE_WINDOW_SECONDS_ENV,
    ),
    "api_access_token": (
        PATREON_API_ACCESS_TOKEN_RATE_LIMIT_ENV,
        PATREON_API_ACCESS_TOKEN_RATE_WINDOW_SECONDS_ENV,
    ),
    "api_edge_4xx": (
        PATREON_API_EDGE_4XX_RATE_LIMIT_ENV,
        PATREON_API_EDGE_4XX_RATE_WINDOW_SECONDS_ENV,
    ),
}
PATREON_RATE_LIMIT_DEFAULTS = {
    "link_request": (
        DEFAULT_PATREON_LINK_REQUEST_RATE_LIMIT,
        DEFAULT_PATREON_LINK_REQUEST_RATE_WINDOW_SECONDS,
    ),
    "proof_request": (
        DEFAULT_PATREON_PROOF_REQUEST_RATE_LIMIT,
        DEFAULT_PATREON_PROOF_REQUEST_RATE_WINDOW_SECONDS,
    ),
    "proof_consume": (
        DEFAULT_PATREON_PROOF_CONSUME_RATE_LIMIT,
        DEFAULT_PATREON_PROOF_CONSUME_RATE_WINDOW_SECONDS,
    ),
    "unlink": (DEFAULT_PATREON_UNLINK_RATE_LIMIT, DEFAULT_PATREON_UNLINK_RATE_WINDOW_SECONDS),
    "status": (DEFAULT_PATREON_STATUS_RATE_LIMIT, DEFAULT_PATREON_STATUS_RATE_WINDOW_SECONDS),
    "s2s": (DEFAULT_PATREON_S2S_RATE_LIMIT, DEFAULT_PATREON_S2S_RATE_WINDOW_SECONDS),
    "webhook_signature_failure": (
        DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_LIMIT,
        DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_WINDOW_SECONDS,
    ),
    "sync_enqueue": (
        DEFAULT_PATREON_SYNC_ENQUEUE_RATE_LIMIT,
        DEFAULT_PATREON_SYNC_ENQUEUE_RATE_WINDOW_SECONDS,
    ),
    "api_client": (
        DEFAULT_PATREON_API_CLIENT_RATE_LIMIT,
        DEFAULT_PATREON_API_CLIENT_RATE_WINDOW_SECONDS,
    ),
    "api_access_token": (
        DEFAULT_PATREON_API_ACCESS_TOKEN_RATE_LIMIT,
        DEFAULT_PATREON_API_ACCESS_TOKEN_RATE_WINDOW_SECONDS,
    ),
    "api_edge_4xx": (
        DEFAULT_PATREON_API_EDGE_4XX_RATE_LIMIT,
        DEFAULT_PATREON_API_EDGE_4XX_RATE_WINDOW_SECONDS,
    ),
}
PATREON_REDIS_RATE_PREFIXES = {
    "link_request": PATREON_LINK_REQUEST_RATE_PREFIX,
    "proof_request": PATREON_PROOF_REQUEST_RATE_PREFIX,
    "proof_consume": PATREON_PROOF_CONSUME_RATE_PREFIX,
    "unlink": PATREON_UNLINK_RATE_PREFIX,
    "status": PATREON_STATUS_RATE_PREFIX,
    "s2s": PATREON_S2S_RATE_PREFIX,
    "webhook_signature_failure": PATREON_WEBHOOK_SIGNATURE_FAILURE_RATE_PREFIX,
    "sync_enqueue": PATREON_SYNC_ENQUEUE_RATE_PREFIX,
    "api_client": PATREON_API_CLIENT_RATE_PREFIX,
    "api_access_token": PATREON_API_ACCESS_TOKEN_RATE_PREFIX,
    "api_edge_4xx": PATREON_API_EDGE_4XX_RATE_PREFIX,
}

DEFAULT_PATREON_SYNC_INTERVAL_SECONDS = 6 * 60 * 60
DEFAULT_PATREON_SYNC_JITTER_SECONDS = 15 * 60
DEFAULT_PATREON_SYNC_STALE_AFTER_SECONDS = 24 * 60 * 60
DEFAULT_PATREON_SYNC_WORKER_POLL_SECONDS = 30
DEFAULT_PATREON_SYNC_WORKER_BATCH_SIZE = 25
DEFAULT_PATREON_SYNC_JOB_LEASE_SECONDS = 5 * 60
DEFAULT_PATREON_SYNC_MAX_ATTEMPTS = 8
DEFAULT_PATREON_SYNC_BACKOFF_SECONDS = (60, 300, 900, 3600, 10800, 21600)
DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_LIMIT = 1
DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_WINDOW_SECONDS = 60

PATREON_SYNC_THRESHOLD_DEFAULTS = {
    PATREON_SYNC_INTERVAL_SECONDS_ENV: DEFAULT_PATREON_SYNC_INTERVAL_SECONDS,
    PATREON_SYNC_JITTER_SECONDS_ENV: DEFAULT_PATREON_SYNC_JITTER_SECONDS,
    PATREON_SYNC_STALE_AFTER_SECONDS_ENV: DEFAULT_PATREON_SYNC_STALE_AFTER_SECONDS,
    PATREON_SYNC_WORKER_POLL_SECONDS_ENV: DEFAULT_PATREON_SYNC_WORKER_POLL_SECONDS,
    PATREON_SYNC_WORKER_BATCH_SIZE_ENV: DEFAULT_PATREON_SYNC_WORKER_BATCH_SIZE,
    PATREON_SYNC_JOB_LEASE_SECONDS_ENV: DEFAULT_PATREON_SYNC_JOB_LEASE_SECONDS,
    PATREON_SYNC_MAX_ATTEMPTS_ENV: DEFAULT_PATREON_SYNC_MAX_ATTEMPTS,
    PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_LIMIT_ENV: (
        DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_LIMIT
    ),
    PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_WINDOW_SECONDS_ENV: (
        DEFAULT_PATREON_WEBHOOK_SIGNATURE_FAILURE_ALERT_WINDOW_SECONDS
    ),
}

PATREON_WEBHOOK_ROUTE = "/webhooks/patreon"
PATREON_AUTH_LINK_REQUEST_ROUTE = "/auth/patreon/link/request"
PATREON_AUTH_LINK_CONFIRM_ROUTE = "/auth/patreon/link/confirm"
PATREON_AUTH_LINK_STATUS_ROUTE = "/auth/patreon/link/status"
PATREON_AUTH_LINK_ROUTE = "/auth/patreon/link"
PATREON_INTERNAL_ENTITLEMENTS_ROUTE_TEMPLATE = "/internal/users/{user_hash}/entitlements"
PATREON_INTERNAL_ENTITLEMENTS_RESYNC_ROUTE_TEMPLATE = (
    "/internal/users/{user_hash}/entitlements/patreon/resync"
)
PATREON_INTERNAL_ENTITLEMENTS_ROUTE_PREFIX = "/internal/users/"
PATREON_INTERNAL_ENTITLEMENTS_ROUTE_SUFFIX = "/entitlements"
PATREON_INTERNAL_ENTITLEMENTS_RESYNC_ROUTE_SUFFIX = "/entitlements/patreon/resync"
PATREON_INTERNAL_S2S_ROUTE_TEMPLATES = (
    PATREON_INTERNAL_ENTITLEMENTS_ROUTE_TEMPLATE,
    PATREON_INTERNAL_ENTITLEMENTS_RESYNC_ROUTE_TEMPLATE,
)

PATREON_WEBHOOK_SIGNATURE_HEADER = "X-Patreon-Signature"
PATREON_WEBHOOK_EVENT_HEADER = "X-Patreon-Event"
PATREON_AUTHORIZATION_HEADER = "Authorization"
PATREON_USER_AGENT_HEADER = "User-Agent"
PATREON_RETRY_AFTER_SECONDS_FIELD = "retry_after_seconds"

PATREON_ALLOWED_MEMBER_WEBHOOK_EVENTS = (
    "members:create",
    "members:update",
    "members:delete",
    "members:pledge:create",
    "members:pledge:update",
    "members:pledge:delete",
)
PATREON_IGNORED_WEBHOOK_EVENTS = (
    "posts:create",
    "posts:publish",
    "posts:update",
    "posts:delete",
)
DEFAULT_PATREON_ALLOWED_WEBHOOK_EVENTS = PATREON_ALLOWED_MEMBER_WEBHOOK_EVENTS
DEFAULT_PATREON_ALLOWED_WEBHOOK_EVENTS_CSV = ",".join(DEFAULT_PATREON_ALLOWED_WEBHOOK_EVENTS)

PATREON_LINK_STATUS_NONE = "none"
PATREON_LINK_STATUS_PENDING = "pending"
PATREON_LINK_STATUS_PROOF_REQUIRED = "proof_required"
PATREON_LINK_STATUS_BLOCKED = "blocked"
PATREON_LINK_STATUS_LINKED = "linked"
PATREON_LINK_STATUS_UNLINKED = "unlinked"
PATREON_LINK_STATUS_REVOKED = "revoked"
PATREON_LINK_STATUS_STALE = "stale"
PATREON_LINK_STATUS_CONFLICT = "conflict"
PATREON_SAFE_LINK_STATUSES = (
    PATREON_LINK_STATUS_NONE,
    PATREON_LINK_STATUS_PENDING,
    PATREON_LINK_STATUS_LINKED,
    PATREON_LINK_STATUS_UNLINKED,
    PATREON_LINK_STATUS_REVOKED,
)

PATREON_ENTITLEMENT_STATUS_ACTIVE = "active"
PATREON_ENTITLEMENT_STATUS_FREE = "free"
PATREON_ENTITLEMENT_STATUS_PENDING = "pending"
PATREON_ENTITLEMENT_STATUS_FORMER = "former"
PATREON_ENTITLEMENT_STATUS_REVOKED = "revoked"
PATREON_ENTITLEMENT_STATUS_STALE = "stale"
PATREON_SAFE_ENTITLEMENT_STATUSES = (
    PATREON_ENTITLEMENT_STATUS_ACTIVE,
    PATREON_ENTITLEMENT_STATUS_FREE,
    PATREON_ENTITLEMENT_STATUS_PENDING,
    PATREON_ENTITLEMENT_STATUS_FORMER,
    PATREON_ENTITLEMENT_STATUS_REVOKED,
    PATREON_ENTITLEMENT_STATUS_STALE,
)
PATREON_DEFAULT_CONTRACT_VERSION = 1

PATREON_SYNC_SOURCE_WEBHOOK = "webhook"
PATREON_SYNC_SOURCE_API_PULL = "api_pull"
PATREON_SYNC_SOURCE_MANUAL_RESYNC = "manual_resync"
PATREON_SYNC_SOURCE_SCHEDULED = "scheduled_sync"
PATREON_SYNC_SOURCE_ADMIN_CORRECTION = "admin_correction"

PATREON_ACTIVITY_CATALOG_RANGE_START = 75
PATREON_ACTIVITY_CATALOG_RANGE_END = 90
PATREON_ACTIVITY_CATALOG_RANGE = {
    "act-cat-075": "patreon_link_proof_requested",
    "act-cat-076": "patreon_link_proof_consumed",
    "act-cat-077": "patreon_linked",
    "act-cat-078": "patreon_link_rejected",
    "act-cat-079": "patreon_unlinked",
    "act-cat-080": "patreon_webhook_received",
    "act-cat-081": "patreon_webhook_rejected",
    "act-cat-082": "patreon_webhook_replay_ignored",
    "act-cat-083": "patreon_sync_started",
    "act-cat-084": "patreon_sync_completed",
    "act-cat-085": "patreon_sync_failed",
    "act-cat-086": "patreon_entitlement_changed",
    "act-cat-087": "patreon_tier_map_miss",
    "act-cat-088": "patreon_token_refreshed",
    "act-cat-089": "patreon_token_revoked",
    "act-cat-090": "patreon_retention_purged",
}
PATREON_ACTIVITY_CATALOG_IDS = tuple(PATREON_ACTIVITY_CATALOG_RANGE)

PATREON_REDACTION_FIELD_NAMES = (
    "patreon_email",
    "patreon_user_email",
    "raw_patreon_email",
    "masked_patreon_email",
    "proof_email",
    "proof_email_hash",
    "proof_email_masked",
    "patreon_user_id",
    "patreon_member_id",
    "patreon_campaign_id",
    "patreon_tier_id",
    "patreon_user_id_hash",
    "patreon_member_id_hash",
    "patreon_campaign_id_hash",
    "patreon_tier_id_hash",
    "patreon_user_id_fingerprint",
    "patreon_member_id_fingerprint",
    "patreon_campaign_id_fingerprint",
    "patreon_tier_id_fingerprint",
    "provider_sub_hash",
    "provider_sub_fingerprint",
    "hash_prefix",
    "provider_email_hash",
    "member_id_hash",
    "campaign_id_hash",
    "tier_id_hash",
    "member_id_fingerprint",
    "campaign_id_fingerprint",
    "tier_id_fingerprint",
    "patron_status",
    "currently_entitled_tiers",
    "last_charge_status",
    "patreon_signature",
    "x_patreon_signature",
    "x-patreon-signature",
    "webhook_secret",
    "patreon_webhook_secret",
    "creator_access_token",
    "creator_refresh_token",
    "patreon_creator_access_token",
    "patreon_creator_refresh_token",
    "patreon_access_token",
    "patreon_refresh_token",
    "patreon_client_secret",
    "patreon_payload",
    "patreon_raw_payload",
    "raw_payload",
    "raw_body",
    "provider_payload",
    "provider_response",
    "audit_rows",
    "delivery_hash",
    "raw_body_sha256",
    "payload_hash",
    "proof_token",
    "proof_secret",
    "token_hash",
    "token_fingerprint",
    "link_token",
    "s2s_token",
    "s2s_bearer_token",
    "patreon_s2s_bearer_token",
    "hmac_secret",
    "id_hmac_secret",
    "provider_token_encryption_key",
    "provider_token_encryption_key_id",
)
PATREON_SENSITIVE_FIELD_NAMES = PATREON_REDACTION_FIELD_NAMES
PATREON_REDACTION_HEADER_NAMES = (
    "authorization",
    "x-patreon-signature",
    "patreon-signature",
    "x-patreon-webhook-secret",
)
PATREON_SENSITIVE_HEADER_NAMES = PATREON_REDACTION_HEADER_NAMES

OAUTH_REDACTION_FIELD_NAMES = (
    "provider_init_token",
    "authorization_code",
    "oauth_code",
    "code",
    "state",
    "oauth_state",
    "nonce",
    "code_verifier",
    "pkce_verifier",
    "id_token",
    "google_id_token",
    "google_id_token_claims",
    "access_token",
    "refresh_token",
    "google_access_token",
    "google_refresh_token",
    "google_sub",
    "provider_sub",
    "google_email",
    "google_hd",
    "oauth_link_token",
    "project_hash",
    "user_group_hash",
    *PATREON_REDACTION_FIELD_NAMES,
)


# Transactional auth email defaults ------------------------------------------
DEFAULT_EMAIL_PROVIDER = os.environ.get(EMAIL_PROVIDER_ENV, "fake").strip().lower() or "fake"
DEFAULT_EMAIL_ACTIVATION_TOKEN_TTL_SECONDS = int(os.environ.get(EMAIL_ACTIVATION_TOKEN_TTL_SECONDS_ENV, "86400"))
DEFAULT_EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS = int(os.environ.get(EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS_ENV, "3600"))
DEFAULT_EMAIL_IDEMPOTENCY_TTL_SECONDS = int(os.environ.get(EMAIL_IDEMPOTENCY_TTL_SECONDS_ENV, "86400"))

EMAIL_SEND_RECIPIENT_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_RECIPIENT_HOURLY_LIMIT_ENV, "3"))
EMAIL_SEND_RECIPIENT_DAILY_LIMIT = int(os.environ.get(EMAIL_SEND_RECIPIENT_DAILY_LIMIT_ENV, "10"))
EMAIL_SEND_USER_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_USER_HOURLY_LIMIT_ENV, "5"))
EMAIL_SEND_IP_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_IP_HOURLY_LIMIT_ENV, "20"))
EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT = int(os.environ.get(EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT_ENV, "5"))
EMAIL_CONSUME_IP_HOURLY_LIMIT = int(os.environ.get(EMAIL_CONSUME_IP_HOURLY_LIMIT_ENV, "30"))
EMAIL_RESEND_COOLDOWN_SECONDS = int(os.environ.get(EMAIL_RESEND_COOLDOWN_SECONDS_ENV, "60"))
EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT = int(os.environ.get(EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT_ENV, "10"))
EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS = int(os.environ.get(EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS_ENV, "900"))

# Password policy / authenticated change-password defaults --------------------
DEFAULT_PASSWORD_MIN_LENGTH = int(os.environ.get(PASSWORD_POLICY_MIN_LENGTH_ENV, "8"))
DEFAULT_PASSWORD_WEAK_DENYLIST = tuple(
    value.strip().lower()
    for value in os.environ.get(
        PASSWORD_POLICY_WEAK_DENYLIST_ENV,
        "password,12345678,123456789,1234567890,qwerty,letmein,admin,password1,"
        "welcome,iloveyou,monkey,dragon,football,baseball,abc123"
    ).split(",")
    if value.strip()
)

AUTH_CHANGE_PASSWORD_FAILURE_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_FAILURE_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS = int(os.environ.get(AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS_ENV, "900"))
AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT_ENV, "20"))

DEFAULT_EMAIL_WORKER_POLL_SECONDS = int(os.environ.get(EMAIL_WORKER_POLL_SECONDS_ENV, "5"))
DEFAULT_EMAIL_WORKER_BATCH_SIZE = int(os.environ.get(EMAIL_WORKER_BATCH_SIZE_ENV, "25"))
DEFAULT_EMAIL_WORKER_LEASE_SECONDS = int(os.environ.get(EMAIL_WORKER_LEASE_SECONDS_ENV, "300"))
DEFAULT_EMAIL_WORKER_MAX_ATTEMPTS = int(os.environ.get(EMAIL_WORKER_MAX_ATTEMPTS_ENV, "8"))
DEFAULT_EMAIL_WORKER_BACKOFF_SECONDS = (10, 30, 120, 600, 1800, 3600, 7200, 14400)
# Retention/PII purge cadence run by the long-running worker. 0 disables it.
DEFAULT_EMAIL_RETENTION_PURGE_INTERVAL_SECONDS = int(
    os.environ.get(EMAIL_RETENTION_PURGE_INTERVAL_SECONDS_ENV, "3600")
)


# Runtime/test environment markers ------------------------------------------
JWT_SECRET_KEY_ENV = "JWT_SECRET_KEY"
APP_ENV_ENV = "APP_ENV"
PYTEST_CURRENT_TEST_ENV = "PYTEST_CURRENT_TEST"
TEST_ENV_NAMES = {"test", "testing", "pytest"}
NON_TEST_ENV_NAMES = {"prod", "production", "stage", "staging", "dev", "development", "local"}
EXPLICIT_TEST_JWT_SECRET = "test_jwt_secret_key_for_testing_only_32chars!!"


# Required JWT claims ---------------------------------------------------------
BASE_REQUIRED_JWT_CLAIMS = ["exp", "iat", "type"]
AUTH_REQUIRED_JWT_CLAIMS = [
    "jti",
    "session_id",
    "family_id",
    "user_hash",
    "collection",
    "scope",
]
