"""Shared authentication lifecycle constants.

Centralizing these values prevents the refresh-token contract from drifting
between routes, JWT helpers, cache helpers, tests, and documentation.
"""

from __future__ import annotations

import os


# Token/cookie names ----------------------------------------------------------
ACCESS_TOKEN_TYPE = "access_token"
REFRESH_TOKEN_TYPE = "refresh_token"
TOKEN_TYPE_BEARER = "Bearer"

ACCESS_COOKIE_NAME = "session_token"
REFRESH_COOKIE_NAME = "refresh_token"

ACCESS_COOKIE_PATH = "/"
REFRESH_COOKIE_PATH = "/auth"
COOKIE_HTTPONLY = True
COOKIE_SECURE = True
COOKIE_SAMESITE = "strict"


# Scope markers ---------------------------------------------------------------
AUTH_SCOPE_PROJECT = "project"
AUTH_SCOPE_PLATFORM = "platform"
PLATFORM_COLLECTION_SENTINEL = "__platform__"


# Redis key prefixes ----------------------------------------------------------
SESSION_PREFIX = "session:"
SESSION_FULL_PREFIX = "session_full:"
REFRESH_FAMILY_PREFIX = "refresh_family:"
REFRESH_TOKEN_PREFIX = "refresh_token:"
REFRESH_ANCHOR_PREFIX = "refresh_anchor:"
REFRESH_USED_PREFIX = "refresh_used:"
REVOKED_FAMILY_PREFIX = "revoked_family:"
USER_SESSIONS_PREFIX = "user_sessions:"
USER_REFRESH_FAMILIES_PREFIX = "user_refresh_families:"
EMAIL_RATE_PREFIX = "email_rate:"
EMAIL_COOLDOWN_PREFIX = "email_cooldown:"
EMAIL_IDEMPOTENCY_CACHE_PREFIX = "email_idem:"
EMAIL_WEBHOOK_EVENT_PREFIX = "email_webhook_event:"
EMAIL_WORKER_WAKE_PREFIX = "email_worker_wake:"
AUTH_CHANGE_PASSWORD_RATE_PREFIX = "auth_change_password_rate:"

# Google OAuth/provider-init Redis key prefixes -------------------------------
GOOGLE_OAUTH_STATE_PREFIX = "google_oauth_state:"
GOOGLE_OAUTH_STATE_CONSUMED_PREFIX = "google_oauth_state_consumed:"
GOOGLE_OAUTH_LINK_TOKEN_PREFIX = "google_oauth_link:"
GOOGLE_OAUTH_RECENT_REAUTH_PREFIX = "google_oauth_reauth:"
GOOGLE_OAUTH_JWKS_CACHE_PREFIX = "google_oauth_jwks:"
GOOGLE_OAUTH_RATE_PREFIX = "google_oauth_rate:"
GOOGLE_OAUTH_START_RATE_PREFIX = "google_oauth_rate:start:"
GOOGLE_OAUTH_CALLBACK_RATE_PREFIX = "google_oauth_rate:callback:"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_PREFIX = "google_oauth_rate:provider_init:"
GOOGLE_OAUTH_STATE_CONSUME_RATE_PREFIX = "google_oauth_rate:state_consume:"
GOOGLE_OAUTH_SUB_COLLISION_RATE_PREFIX = "google_oauth_rate:sub_collision:"
GOOGLE_OAUTH_LINK_TOKEN_RATE_PREFIX = "google_oauth_rate:link_token:"
GOOGLE_OAUTH_JWKS_FETCH_RATE_PREFIX = "google_oauth_rate:jwks_fetch:"
GOOGLE_OAUTH_UNLINK_RATE_PREFIX = "google_oauth_rate:unlink:"
PROVIDER_INIT_REDEEM_CACHE_PREFIX = "provider_init_redeem:"


# TTL/config names ------------------------------------------------------------
REFRESH_FAMILY_TTL_SECONDS = 72 * 60 * 60
REMEMBER_ME_REFRESH_TTL_SECONDS = 30 * 24 * 60 * 60
JWT_ACCESS_TOKEN_EXPIRE_MINUTES_ENV = "JWT_ACCESS_TOKEN_EXPIRE_MINUTES"
DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = int(
    os.environ.get(JWT_ACCESS_TOKEN_EXPIRE_MINUTES_ENV, "15")
)


# Transactional auth email config names ---------------------------------------
EMAIL_DELIVERY_ENABLED_ENV = "EMAIL_DELIVERY_ENABLED"
EMAIL_PROVIDER_ENV = "EMAIL_PROVIDER"
EMAIL_ALLOW_REAL_SEND_IN_TESTS_ENV = "EMAIL_ALLOW_REAL_SEND_IN_TESTS"
EMAIL_FROM_ADDRESS_ENV = "EMAIL_FROM_ADDRESS"
EMAIL_REPLY_TO_ADDRESS_ENV = "EMAIL_REPLY_TO_ADDRESS"
EMAIL_SENDER_DOMAIN_VERIFIED_ENV = "EMAIL_SENDER_DOMAIN_VERIFIED"

RESEND_API_KEY_ENV = "RESEND_API_KEY"
RESEND_WEBHOOK_SECRET_ENV = "RESEND_WEBHOOK_SECRET"
RESEND_WEBHOOK_TOLERANCE_SECONDS_ENV = "RESEND_WEBHOOK_TOLERANCE_SECONDS"

MAILPIT_SMTP_HOST_ENV = "MAILPIT_SMTP_HOST"
MAILPIT_SMTP_PORT_ENV = "MAILPIT_SMTP_PORT"
MAILPIT_API_BASE_URL_ENV = "MAILPIT_API_BASE_URL"

EMAIL_TOKEN_PEPPER_ENV = "EMAIL_TOKEN_PEPPER"
EMAIL_HASH_PEPPER_ENV = "EMAIL_HASH_PEPPER"
EMAIL_IDEMPOTENCY_PEPPER_ENV = "EMAIL_IDEMPOTENCY_PEPPER"
EMAIL_PAYLOAD_KEY_ENV = "EMAIL_PAYLOAD_KEY"

EMAIL_ACTIVATION_TOKEN_TTL_SECONDS_ENV = "EMAIL_ACTIVATION_TOKEN_TTL_SECONDS"
EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS_ENV = "EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS"
EMAIL_IDEMPOTENCY_TTL_SECONDS_ENV = "EMAIL_IDEMPOTENCY_TTL_SECONDS"
EMAIL_TERMINAL_RETENTION_DAYS_ENV = "EMAIL_TERMINAL_RETENTION_DAYS"
EMAIL_DELIVERY_ATTEMPT_RETENTION_DAYS_ENV = "EMAIL_DELIVERY_ATTEMPT_RETENTION_DAYS"

EMAIL_SEND_RECIPIENT_HOURLY_LIMIT_ENV = "EMAIL_SEND_RECIPIENT_HOURLY_LIMIT"
EMAIL_SEND_RECIPIENT_DAILY_LIMIT_ENV = "EMAIL_SEND_RECIPIENT_DAILY_LIMIT"
EMAIL_SEND_USER_HOURLY_LIMIT_ENV = "EMAIL_SEND_USER_HOURLY_LIMIT"
EMAIL_SEND_IP_HOURLY_LIMIT_ENV = "EMAIL_SEND_IP_HOURLY_LIMIT"
EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT_ENV = "EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT"
EMAIL_CONSUME_IP_HOURLY_LIMIT_ENV = "EMAIL_CONSUME_IP_HOURLY_LIMIT"
EMAIL_RESEND_COOLDOWN_SECONDS_ENV = "EMAIL_RESEND_COOLDOWN_SECONDS"
EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT_ENV = "EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT"
EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS_ENV = "EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS"

PASSWORD_POLICY_MIN_LENGTH_ENV = "PASSWORD_POLICY_MIN_LENGTH"
PASSWORD_POLICY_WEAK_DENYLIST_ENV = "PASSWORD_POLICY_WEAK_DENYLIST"

AUTH_CHANGE_PASSWORD_FAILURE_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_FAILURE_LIMIT"
AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS_ENV = "AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS"
AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT"
AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT"
AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT_ENV = "AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT"

EMAIL_WORKER_POLL_SECONDS_ENV = "EMAIL_WORKER_POLL_SECONDS"
EMAIL_WORKER_BATCH_SIZE_ENV = "EMAIL_WORKER_BATCH_SIZE"
EMAIL_WORKER_LEASE_SECONDS_ENV = "EMAIL_WORKER_LEASE_SECONDS"
EMAIL_WORKER_MAX_ATTEMPTS_ENV = "EMAIL_WORKER_MAX_ATTEMPTS"
EMAIL_WORKER_BACKOFF_SECONDS_ENV = "EMAIL_WORKER_BACKOFF_SECONDS"
EMAIL_RETENTION_PURGE_INTERVAL_SECONDS_ENV = "EMAIL_RETENTION_PURGE_INTERVAL_SECONDS"


# Google OAuth/provider-init config names -------------------------------------
GOOGLE_OAUTH_ENABLED_ENV = "GOOGLE_OAUTH_ENABLED"
GOOGLE_OAUTH_CLIENT_ID_ENV = "GOOGLE_OAUTH_CLIENT_ID"
GOOGLE_OAUTH_CLIENT_SECRET_ENV = "GOOGLE_OAUTH_CLIENT_SECRET"
GOOGLE_OAUTH_DISCOVERY_URL_ENV = "GOOGLE_OAUTH_DISCOVERY_URL"
GOOGLE_OAUTH_AUTHORIZE_ENDPOINT_ENV = "GOOGLE_OAUTH_AUTHORIZE_ENDPOINT"
GOOGLE_OAUTH_TOKEN_ENDPOINT_ENV = "GOOGLE_OAUTH_TOKEN_ENDPOINT"
GOOGLE_OAUTH_JWKS_URI_ENV = "GOOGLE_OAUTH_JWKS_URI"
GOOGLE_OAUTH_ISSUERS_ENV = "GOOGLE_OAUTH_ISSUERS"
GOOGLE_OAUTH_SCOPES_ENV = "GOOGLE_OAUTH_SCOPES"
GOOGLE_OAUTH_REDIRECT_URIS_ENV = "GOOGLE_OAUTH_REDIRECT_URIS"
GOOGLE_OAUTH_RETURN_ORIGINS_ENV = "GOOGLE_OAUTH_RETURN_ORIGINS"
GOOGLE_OAUTH_PROVISIONING_MODE_ENV = "GOOGLE_OAUTH_PROVISIONING_MODE"
GOOGLE_OAUTH_DEFAULT_USER_GROUP_HASH_ENV = "GOOGLE_OAUTH_DEFAULT_USER_GROUP_HASH"
GOOGLE_OAUTH_STATE_TTL_SECONDS_ENV = "GOOGLE_OAUTH_STATE_TTL_SECONDS"
GOOGLE_OAUTH_LINK_TOKEN_TTL_SECONDS_ENV = "GOOGLE_OAUTH_LINK_TOKEN_TTL_SECONDS"
GOOGLE_OAUTH_RECENT_REAUTH_SECONDS_ENV = "GOOGLE_OAUTH_RECENT_REAUTH_SECONDS"
GOOGLE_OAUTH_JWKS_CACHE_TTL_SECONDS_ENV = "GOOGLE_OAUTH_JWKS_CACHE_TTL_SECONDS"
GOOGLE_OAUTH_LEEWAY_SECONDS_ENV = "GOOGLE_OAUTH_LEEWAY_SECONDS"
GOOGLE_OAUTH_STATE_PEPPER_ENV = "GOOGLE_OAUTH_STATE_PEPPER"
GOOGLE_OAUTH_PROVIDER_SUB_PEPPER_ENV = "GOOGLE_OAUTH_PROVIDER_SUB_PEPPER"
GOOGLE_OAUTH_EMAIL_HASH_PEPPER_ENV = "GOOGLE_OAUTH_EMAIL_HASH_PEPPER"
GOOGLE_OAUTH_PASSWORDLESS_HASH_SECRET_ENV = "GOOGLE_OAUTH_PASSWORDLESS_HASH_SECRET"
GOOGLE_OAUTH_FAIL_CLOSED_ON_REDIS_ERROR_ENV = "GOOGLE_OAUTH_FAIL_CLOSED_ON_REDIS_ERROR"
PROVIDER_INIT_REDEEM_URL_ENV = "PROVIDER_INIT_REDEEM_URL"
PROVIDER_INIT_REDEEM_TOKEN_ENV = "PROVIDER_INIT_REDEEM_TOKEN"
PROVIDER_INIT_RETURN_ORIGINS_ENV = "PROVIDER_INIT_RETURN_ORIGINS"

GOOGLE_OAUTH_START_RATE_LIMIT_ENV = "GOOGLE_OAUTH_START_RATE_LIMIT"
GOOGLE_OAUTH_START_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_START_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_CALLBACK_RATE_LIMIT_ENV = "GOOGLE_OAUTH_CALLBACK_RATE_LIMIT"
GOOGLE_OAUTH_CALLBACK_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_CALLBACK_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_LIMIT_ENV = "GOOGLE_OAUTH_PROVIDER_INIT_RATE_LIMIT"
GOOGLE_OAUTH_PROVIDER_INIT_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_PROVIDER_INIT_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_STATE_CONSUME_RATE_LIMIT_ENV = "GOOGLE_OAUTH_STATE_CONSUME_RATE_LIMIT"
GOOGLE_OAUTH_STATE_CONSUME_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_STATE_CONSUME_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_SUB_COLLISION_RATE_LIMIT_ENV = "GOOGLE_OAUTH_SUB_COLLISION_RATE_LIMIT"
GOOGLE_OAUTH_SUB_COLLISION_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_SUB_COLLISION_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_LINK_TOKEN_RATE_LIMIT_ENV = "GOOGLE_OAUTH_LINK_TOKEN_RATE_LIMIT"
GOOGLE_OAUTH_LINK_TOKEN_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_LINK_TOKEN_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_JWKS_FETCH_RATE_LIMIT_ENV = "GOOGLE_OAUTH_JWKS_FETCH_RATE_LIMIT"
GOOGLE_OAUTH_JWKS_FETCH_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_JWKS_FETCH_RATE_WINDOW_SECONDS"
GOOGLE_OAUTH_UNLINK_RATE_LIMIT_ENV = "GOOGLE_OAUTH_UNLINK_RATE_LIMIT"
GOOGLE_OAUTH_UNLINK_RATE_WINDOW_SECONDS_ENV = "GOOGLE_OAUTH_UNLINK_RATE_WINDOW_SECONDS"

GOOGLE_OAUTH_PROVISIONING_DISABLED = "disabled"
GOOGLE_OAUTH_PROVISIONING_LINK_ONLY = "link_only"
GOOGLE_OAUTH_PROVISIONING_AUTO_CREATE = "auto_create"
GOOGLE_OAUTH_PROVISIONING_BOTH = "both"
GOOGLE_OAUTH_ALLOWED_PROVISIONING_MODES = {
    GOOGLE_OAUTH_PROVISIONING_DISABLED,
    GOOGLE_OAUTH_PROVISIONING_LINK_ONLY,
    GOOGLE_OAUTH_PROVISIONING_AUTO_CREATE,
    GOOGLE_OAUTH_PROVISIONING_BOTH,
}
GOOGLE_OAUTH_DEFAULT_SCOPES = "openid email"

OAUTH_REDACTION_FIELD_NAMES = (
    "provider_init_token",
    "authorization_code",
    "oauth_code",
    "code",
    "state",
    "oauth_state",
    "nonce",
    "code_verifier",
    "pkce_verifier",
    "id_token",
    "google_id_token",
    "google_id_token_claims",
    "access_token",
    "refresh_token",
    "google_access_token",
    "google_refresh_token",
    "google_sub",
    "provider_sub",
    "google_email",
    "google_hd",
    "oauth_link_token",
    "project_hash",
    "user_group_hash",
)


# Transactional auth email defaults ------------------------------------------
DEFAULT_EMAIL_PROVIDER = os.environ.get(EMAIL_PROVIDER_ENV, "fake").strip().lower() or "fake"
DEFAULT_EMAIL_ACTIVATION_TOKEN_TTL_SECONDS = int(os.environ.get(EMAIL_ACTIVATION_TOKEN_TTL_SECONDS_ENV, "86400"))
DEFAULT_EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS = int(os.environ.get(EMAIL_PASSWORD_RESET_TOKEN_TTL_SECONDS_ENV, "3600"))
DEFAULT_EMAIL_IDEMPOTENCY_TTL_SECONDS = int(os.environ.get(EMAIL_IDEMPOTENCY_TTL_SECONDS_ENV, "86400"))

EMAIL_SEND_RECIPIENT_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_RECIPIENT_HOURLY_LIMIT_ENV, "3"))
EMAIL_SEND_RECIPIENT_DAILY_LIMIT = int(os.environ.get(EMAIL_SEND_RECIPIENT_DAILY_LIMIT_ENV, "10"))
EMAIL_SEND_USER_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_USER_HOURLY_LIMIT_ENV, "5"))
EMAIL_SEND_IP_HOURLY_LIMIT = int(os.environ.get(EMAIL_SEND_IP_HOURLY_LIMIT_ENV, "20"))
EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT = int(os.environ.get(EMAIL_CONSUME_LOOKUP_HOURLY_LIMIT_ENV, "5"))
EMAIL_CONSUME_IP_HOURLY_LIMIT = int(os.environ.get(EMAIL_CONSUME_IP_HOURLY_LIMIT_ENV, "30"))
EMAIL_RESEND_COOLDOWN_SECONDS = int(os.environ.get(EMAIL_RESEND_COOLDOWN_SECONDS_ENV, "60"))
EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT = int(os.environ.get(EMAIL_LOGIN_IDENTIFIER_FAILURE_LIMIT_ENV, "10"))
EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS = int(os.environ.get(EMAIL_LOGIN_IDENTIFIER_FAILURE_WINDOW_SECONDS_ENV, "900"))

# Password policy / authenticated change-password defaults --------------------
DEFAULT_PASSWORD_MIN_LENGTH = int(os.environ.get(PASSWORD_POLICY_MIN_LENGTH_ENV, "8"))
DEFAULT_PASSWORD_WEAK_DENYLIST = tuple(
    value.strip().lower()
    for value in os.environ.get(
        PASSWORD_POLICY_WEAK_DENYLIST_ENV,
        "password,12345678,123456789,1234567890,qwerty,letmein,admin,password1,"
        "welcome,iloveyou,monkey,dragon,football,baseball,abc123"
    ).split(",")
    if value.strip()
)

AUTH_CHANGE_PASSWORD_FAILURE_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_FAILURE_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS = int(os.environ.get(AUTH_CHANGE_PASSWORD_FAILURE_WINDOW_SECONDS_ENV, "900"))
AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_USER_HOURLY_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_SESSION_HOURLY_LIMIT_ENV, "5"))
AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT = int(os.environ.get(AUTH_CHANGE_PASSWORD_IP_HOURLY_LIMIT_ENV, "20"))

DEFAULT_EMAIL_WORKER_POLL_SECONDS = int(os.environ.get(EMAIL_WORKER_POLL_SECONDS_ENV, "5"))
DEFAULT_EMAIL_WORKER_BATCH_SIZE = int(os.environ.get(EMAIL_WORKER_BATCH_SIZE_ENV, "25"))
DEFAULT_EMAIL_WORKER_LEASE_SECONDS = int(os.environ.get(EMAIL_WORKER_LEASE_SECONDS_ENV, "300"))
DEFAULT_EMAIL_WORKER_MAX_ATTEMPTS = int(os.environ.get(EMAIL_WORKER_MAX_ATTEMPTS_ENV, "8"))
DEFAULT_EMAIL_WORKER_BACKOFF_SECONDS = (10, 30, 120, 600, 1800, 3600, 7200, 14400)
# Retention/PII purge cadence run by the long-running worker. 0 disables it.
DEFAULT_EMAIL_RETENTION_PURGE_INTERVAL_SECONDS = int(
    os.environ.get(EMAIL_RETENTION_PURGE_INTERVAL_SECONDS_ENV, "3600")
)


# Runtime/test environment markers ------------------------------------------
JWT_SECRET_KEY_ENV = "JWT_SECRET_KEY"
APP_ENV_ENV = "APP_ENV"
PYTEST_CURRENT_TEST_ENV = "PYTEST_CURRENT_TEST"
TEST_ENV_NAMES = {"test", "testing", "pytest"}
NON_TEST_ENV_NAMES = {"prod", "production", "stage", "staging", "dev", "development", "local"}
EXPLICIT_TEST_JWT_SECRET = "test_jwt_secret_key_for_testing_only_32chars!!"


# Required JWT claims ---------------------------------------------------------
BASE_REQUIRED_JWT_CLAIMS = ["exp", "iat", "type"]
AUTH_REQUIRED_JWT_CLAIMS = [
    "jti",
    "session_id",
    "family_id",
    "user_hash",
    "collection",
    "scope",
]
